package entity;
// default package
// Generated Oct 21, 2013 10:26:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorizationsEmployeeEmployee generated by hbm2java
 */
public class AuthorizationsEmployeeEmployee{

	private int authorizationId;
	private String authorizedBy;
	private String authorizedTo;

	public AuthorizationsEmployeeEmployee() {
	}

	public AuthorizationsEmployeeEmployee(int authorizationId,
			String authorizedBy, String authorizedTo) {
		this.authorizationId = authorizationId;
		this.authorizedBy = authorizedBy;
		this.authorizedTo = authorizedTo;
	}

	public int getAuthorizationId() {
		return this.authorizationId;
	}

	public void setAuthorizationId(int authorizationId) {
		this.authorizationId = authorizationId;
	}

	public String getAuthorizedBy() {
		return this.authorizedBy;
	}

	public void setAuthorizedBy(String authorizedBy) {
		this.authorizedBy = authorizedBy;
	}

	public String getAuthorizedTo() {
		return this.authorizedTo;
	}

	public void setAuthorizedTo(String authorizedTo) {
		this.authorizedTo = authorizedTo;
	}

}
