package entity;

// default package
// Generated Oct 21, 2013 10:26:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * Credentials generated by hbm2java
 */
public class Credentials {

	private String userId;
	private String passwordHash;
	private int otpDone;
	int enabled;

	public int getEnabled() {
		return enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

	public int getOtpDone() {
		return otpDone;
	}

	public void setOtpDone(int otpDone) {
		this.otpDone = otpDone;
	}

	public Credentials() {
	}

	public Credentials(String userId, String passwordHash) {
		this.userId = userId;
		this.passwordHash = passwordHash;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public void setPasswordHash(String passwordHash) {
		this.passwordHash = passwordHash;
	}

	public String getPasswordHash() {
		return passwordHash;
	}

}
