package entity;

// default package
// Generated Oct 21, 2013 10:26:11 PM by Hibernate Tools 3.4.0.CR1
import javax.persistence.Entity;
/**
 * ExternalUsers generated by hbm2java
 */
@Entity
public class criticalTransactions {

	private int authId;
	private int transactionId;
	private String authGivenby;
	private String authGivento;

	public criticalTransactions() {
	}

	public criticalTransactions(int authId,int transactionId,
								String authGivenby, String authGivento) {
		this.authId = authId;
		this.transactionId = transactionId;
		this.authGivenby = authGivenby;
		this.authGivento = authGivento;
	}

	public int getAuthId() {
		return authId;
	}

	public void setAuthId(int authId) {
		this.authId = authId;
	}

	public int getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	public String getAuthGivenby() {
		return authGivenby;
	}

	public void setAuthGivenby(String authGivenby) {
		this.authGivenby = authGivenby;
	}

	public String getAuthGivento() {
		return authGivento;
	}

	public void setAuthGivento(String authGivento) {
		this.authGivento = authGivento;
	}



}
