package entity;

// default package
// Generated Oct 21, 2013 10:26:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExternalUsers generated by hbm2java
 */
public class ExternalUsers {

	private int user_type;
	private String userName, email_id, userId;
	double balance_amount;

	public int getUser_type() {
		return user_type;
	}

	public void setUser_type(int user_type) {
		this.user_type = user_type;
	}

	public String getEmail_id() {
		return email_id;
	}

	public void setEmail_id(String email_id) {
		this.email_id = email_id;
	}

	public ExternalUsers() {
	}

	public ExternalUsers(String userId, String userName) {
		this.userId = userId;
		this.userName = userName;
	}

	public double getBalance_amount() {
		return balance_amount;
	}

	public void setBalance_amount(double balance_amount) {
		this.balance_amount = balance_amount;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
