package entity;

import javax.persistence.Entity;
// default package
// Generated Oct 21, 2013 10:26:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * InternalUsers generated by hbm2java
 */

@Entity
public class InternalUsers {

	private String userId;
	private String userName, userEmail;

	public String getUserEmail() {
		return userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	private int dept_sales, dept_it, dept_tm, dept_hr, dept_cm;
	private int userRole;

	public InternalUsers() {
	}

	public InternalUsers(String userId, String userName, int dept_sales,
			int dept_it, int dept_tm, int dept_hr, int dept_cm, int userRole) {
		super();
		this.userId = userId;
		this.userName = userName;
		this.dept_sales = dept_sales;
		this.dept_it = dept_it;
		this.dept_tm = dept_tm;
		this.dept_hr = dept_hr;
		this.dept_cm = dept_cm;
		this.userRole = userRole;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public int getUserRole() {
		return this.userRole;
	}

	public int getDept_sales() {
		return dept_sales;
	}

	public void setDept_sales(int dept_sales) {
		this.dept_sales = dept_sales;
	}

	public int getDept_it() {
		return dept_it;
	}

	public void setDept_it(int dept_it) {
		this.dept_it = dept_it;
	}

	public int getDept_tm() {
		return dept_tm;
	}

	public void setDept_tm(int dept_tm) {
		this.dept_tm = dept_tm;
	}

	public int getDept_hr() {
		return dept_hr;
	}

	public void setDept_hr(int dept_hr) {
		this.dept_hr = dept_hr;
	}

	public int getDept_cm() {
		return dept_cm;
	}

	public void setDept_cm(int dept_cm) {
		this.dept_cm = dept_cm;
	}

	public void setUserRole(int userRole) {
		this.userRole = userRole;
	}

}
