package entity;

// default package
// Generated Oct 21, 2013 10:26:11 PM by Hibernate Tools 3.4.0.CR1
import javax.persistence.Entity;

/**
 * PendingMerchantPayments generated by hbm2java
 */
@Entity
public class PendingMerchantPayments {

	private int paymentId;

	public PendingMerchantPayments() {
		super();
	}

	public int getPaymentId() {
		return paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	public int getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	public String getCustomerUserId() {
		return customerUserId;
	}

	public void setCustomerUserId(String customerUserId) {
		this.customerUserId = customerUserId;
	}

	public String getMerchantUserId() {
		return merchantUserId;
	}

	public void setMerchantUserId(String merchantUserId) {
		this.merchantUserId = merchantUserId;
	}

	public PendingMerchantPayments(int paymentId, int transactionId,
			String customerUserId, String merchantUserId) {
		super();
		this.paymentId = paymentId;
		this.transactionId = transactionId;
		this.customerUserId = customerUserId;
		this.merchantUserId = merchantUserId;
	}

	private int transactionId;
	private String customerUserId;
	private String merchantUserId;

}
