package entity;

// default package
// Generated Oct 21, 2013 10:26:11 PM by Hibernate Tools 3.4.0.CR1
import javax.persistence.Entity;

/**
 * ExternalUsers generated by hbm2java
 */
@Entity
public class PendingExternalUserRequests {

	private int requestId;
	private int userType, requestType;
	private String userId;
	private String userName, emailId;

	public PendingExternalUserRequests() {
	}
	
	public int getRequestId() {
		return requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	public int getUserType() {
		return userType;
	}

	public void setUserType(int userType) {
		this.userType = userType;
	}

	public int getRequestType() {
		return requestType;
	}

	public void setRequestType(int requestType) {
		this.requestType = requestType;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public PendingExternalUserRequests(int requestId, int userType,
			int requestType, String userId, String userName, String emailId) {
		this.requestId = requestId;
		this.userType = userType;
		this.requestType = requestType;
		this.userId = userId;
		this.userName = userName;
		this.emailId = emailId;
	}

}
